extends SceneTree
const Storage = preload("res://player_storage.gd")
const Bindings = preload("res://input_bindings.gd")
const Mods = preload("res://mod_registry.gd")
const Saves = preload("res://save_games.gd")
const Paths = preload("res://asset_paths.gd")
const Game = preload("res://game.gd")
const Editor = preload("res://asset_editor.gd")
const Video = preload("res://video_preview.gd")
var failures := 0
var checks := 0
func check(ok: bool, message: String) -> void:
	checks += 1
	if not ok: failures += 1; push_error(message)
func _initialize() -> void: call_deferred("run")
func run() -> void:
	check(Storage.root_path() == OS.get_system_dir(OS.SYSTEM_DIR_DOCUMENTS).path_join("OpenSC"),"Uses the OS Documents directory")
	Storage.root_override = "res://tests/storage-fixtures"
	var preferences := Storage.preferences_path()
	check(Saves.new().folder == Storage.saves_path(),"Save games use the new savegame directory")
	check(Storage.ensure_parent(preferences) == OK,"Creates the preference directory")
	var config := ConfigFile.new()
	config.set_value("game","folder",ProjectSettings.globalize_path("res://../Original Sub Culture"))
	config.set_value("video","ffmpeg","example-decoder")
	check(config.save(preferences) == OK,"Writes asset and decoder preferences")
	Bindings.reset_defaults()
	check(Bindings.set_binding("map_toggle",0,{"kind":"key","code":KEY_Z,"physical":false,"ctrl":false,"alt":false,"shift":false,"meta":false}),"Changes a binding")
	check(Bindings.save_settings() == OK,"Saves controls to the shared preferences file")
	Mods.initialize(false)
	check(Mods.preference_path == preferences,"Mods use the shared preferences file")
	check(Mods.apply([],[],true) == OK,"Saves mod preferences")
	config.load(preferences)
	check(config.has_section("bindings") and config.has_section("mods") and config.get_value("video","ffmpeg") == "example-decoder","Mod and control writes preserve other preference sections")
	var video := Video.new(); video.set_decoder("updated-decoder"); video.free()
	config.load(preferences)
	check(config.has_section("bindings") and config.has_section("mods") and config.has_section("game") and config.get_value("video","ffmpeg") == "updated-decoder","Decoder preferences preserve controls, mods and asset paths")
	Bindings.reset_defaults(); Bindings.load_settings()
	check(Bindings.bindings.map_toggle[0].code == KEY_Z,"Reloads controls from Documents preferences")
	check(not Paths.find_game_folder().is_empty(),"Asset discovery reads the new preferences")
	var saves := Saves.new()
	var explored := PackedByteArray(); explored.resize(preload("res://hud_map.gd").RESOLUTION ** 2)
	var snapshot := {"version":1,"dock":{"id":0},"name":"Storage test","saved_at":"test","map_signature":"test","pose":[1,0,0,0,1,0,0,0,1,0,0,0],"hour":12.0,"equipment":[],"weapons":[],"explored":Marshalls.raw_to_base64(explored)}
	check(saves.write(0,snapshot) == OK,"Saves a game in the new directory")
	check(saves.read(0).get("name") == "Storage test","Reads the saved game back")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(saves.path(0)))
	DirAccess.remove_absolute(ProjectSettings.globalize_path(Storage.saves_path()))
	DirAccess.remove_absolute(ProjectSettings.globalize_path(preferences))
	DirAccess.remove_absolute(ProjectSettings.globalize_path(Storage.root_path()))
	print("Player storage: %d checks, %d failures" % [checks,failures])
	quit(1 if failures else 0)
